"""
HashPilot PDF Report Service
"""

from datetime import datetime
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


class ReportService:

    @staticmethod
    def generate_report(results, analysis, system_info):

        buffer = BytesIO()

        doc = SimpleDocTemplate(buffer)

        styles = getSampleStyleSheet()

        elements = []

        elements.append(
            Paragraph(
                "<b><font size=22>HashPilot Benchmark Report</font></b>",
                styles["Title"],
            )
        )

        elements.append(Spacer(1, 20))

        elements.append(
            Paragraph(
                f"Generated: {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}",
                styles["Normal"],
            )
        )

        elements.append(Spacer(1, 20))

        elements.append(Paragraph("<b>System Information</b>", styles["Heading2"]))

        system_table = Table(
            [
                ["CPU", system_info["cpu"]],
                ["RAM", f'{system_info["ram_gb"]} GB'],
                ["Operating System", system_info["os"]],
                ["Python", system_info["python"]],
                ["Threads", system_info["logical_threads"]],
            ]
        )

        system_table.setStyle(
            TableStyle(
                [
                    ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                    ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ]
            )
        )

        elements.append(system_table)

        elements.append(Spacer(1, 25))

        elements.append(Paragraph("<b>AI Recommendation</b>", styles["Heading2"]))

        elements.append(
            Paragraph(
                f"Recommended Strategy : <b>{analysis['recommended_strategy']}</b>",
                styles["Normal"],
            )
        )

        elements.append(
            Paragraph(
                f"Confidence : <b>{analysis['confidence']}%</b>",
                styles["Normal"],
            )
        )

        elements.append(Spacer(1, 20))

        elements.append(Paragraph("<b>Benchmark Results</b>", styles["Heading2"]))

        table_data = [
            [
                "Strategy",
                "Runtime (s)",
                "Attempts",
                "Hash Rate",
            ]
        ]

        for item in results:

            table_data.append(
                [
                    item["strategy"],
                    f'{item["time"]:.4f}',
                    f'{item["attempts"]:,}',
                    f'{item["hashrate"]:.0f}',
                ]
            )

        benchmark_table = Table(table_data)

        benchmark_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                    ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ]
            )
        )

        elements.append(benchmark_table)

        elements.append(Spacer(1, 30))

        elements.append(
            Paragraph(
                "<i>Generated by HashPilot v1.0</i>",
                styles["Normal"],
            )
        )

        doc.build(elements)

        buffer.seek(0)

        return buffer
